app: mvp-dpd
service: mvp-dpd
variablesResolutionMode: '20210326'
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  stage: sandpit
  timeout: 29 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  lambdaHashingVersion: '20201221'

functions:
  mvp-dpd:
    handler: apps/dist/handler.handler
    events:
      - httpApi: '*'
