service: multiprotocol-verfifier
variablesResolutionMode: '20210326'

plugins:
  - serverless-bundle

custom:
  bundle:
    tsConfig: 'tsconfig.json'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  stage: sandpit
  timeout: 29 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  lambdaHashingVersion: '20201221'

functions:
  verifier:
    handler: src/lambda.handler
    events:
      - httpApi: '*'
